# Generated by Django 4.2.7 on 2025-05-27 20:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("active", "Active"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="initializing",
                        max_length=20,
                    ),
                ),
                ("sam2_session_id", models.CharField(blank=True, max_length=100)),
                ("target_materials", models.JSONField(default=list)),
                (
                    "analysis_type",
                    models.CharField(default="thermal_anomaly", max_length=50),
                ),
                ("total_frames_analyzed", models.IntegerField(default=0)),
                ("total_objects_tracked", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to="buildings.buildingproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to="buildings.videofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuildingMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("masonry", "Masonry"),
                            ("metal", "Metal"),
                            ("wood", "Wood"),
                            ("glass", "Glass"),
                            ("insulation", "Insulation"),
                            ("roofing", "Roofing"),
                            ("concrete", "Concrete"),
                            ("composite", "Composite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("thermal_conductivity", models.FloatField(blank=True, null=True)),
                ("specific_heat", models.FloatField(blank=True, null=True)),
                ("density", models.FloatField(blank=True, null=True)),
                ("emissivity", models.FloatField(blank=True, null=True)),
                ("typical_temp_min", models.FloatField(blank=True, null=True)),
                ("typical_temp_max", models.FloatField(blank=True, null=True)),
                ("visual_features", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SegmentationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_index", models.IntegerField()),
                ("object_id", models.IntegerField()),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Segmentation"),
                            ("propagated", "Propagated Segmentation"),
                            ("manual_refined", "Manually Refined"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mask_rle_counts", models.TextField()),
                ("mask_rle_size", models.JSONField()),
                ("mask_area_pixels", models.IntegerField()),
                ("identified_material", models.CharField(blank=True, max_length=100)),
                ("material_confidence", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("thermal_anomaly_score", models.FloatField(blank=True, null=True)),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "bounding_box",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("prediction_confidence", models.FloatField(blank=True, null=True)),
                ("edge_quality_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["frame_index", "object_id"],
            },
        ),
        migrations.CreateModel(
            name="ThermalAnomalyDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("hot_spot", "Hot Spot"),
                            ("cold_spot", "Cold Spot"),
                            ("thermal_bridge", "Thermal Bridge"),
                            ("insulation_defect", "Insulation Defect"),
                            ("air_leakage", "Air Leakage"),
                            ("moisture_intrusion", "Moisture Intrusion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("temperature_deviation", models.FloatField()),
                ("baseline_temperature", models.FloatField()),
                ("affected_area_sqm", models.FloatField(blank=True, null=True)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("recommended_action", models.TextField(blank=True)),
                ("priority_level", models.IntegerField(default=3)),
                ("estimated_cost_impact", models.CharField(blank=True, max_length=20)),
                ("acknowledged", models.BooleanField(default=False)),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segmentation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="analysis.segmentationresult",
                    ),
                ),
            ],
            options={
                "ordering": ["priority_level", "-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="ClickPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_index", models.IntegerField()),
                ("object_id", models.IntegerField()),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive Point"),
                            ("negative", "Negative Point"),
                            ("box", "Bounding Box"),
                        ],
                        max_length=20,
                    ),
                ),
                ("coordinates", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="analysis.analysissession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["frame_index", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="segmentationresult",
            index=models.Index(
                fields=["analysis_session", "frame_index"],
                name="analysis_se_analysi_dd712e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationresult",
            index=models.Index(
                fields=["analysis_session", "object_id"],
                name="analysis_se_analysi_187af3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="segmentationresult",
            index=models.Index(
                fields=["identified_material"], name="analysis_se_identif_cfc1a4_idx"
            ),
        ),
    ]
