# Generated by Django 4.2.7 on 2025-05-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysissession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Analysis Session",
                "verbose_name_plural": "Analysis Sessions",
            },
        ),
        migrations.AddField(
            model_name="analysissession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="confidence_threshold",
            field=models.FloatField(
                default=0.5, help_text="Minimum confidence threshold for detections"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="enable_tracking",
            field=models.BooleanField(
                default=True, help_text="Enable object tracking across frames"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if analysis fails"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="max_memory_frames",
            field=models.IntegerField(
                default=5, help_text="Maximum number of frames to keep in GPU memory"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="offload_to_cpu",
            field=models.BooleanField(
                default=True, help_text="Offload video frames to CPU to save GPU memory"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="results_summary",
            field=models.JSONField(
                blank=True, default=dict, help_text="Summary of analysis results"
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="sam2_model",
            field=models.CharField(
                choices=[
                    ("tiny", "SAM 2 Tiny (38.9M params) - Fast, low memory"),
                    ("small", "SAM 2 Small (46.0M params) - Balanced"),
                    ("base_plus", "SAM 2 Base Plus (80.8M params) - High quality"),
                    (
                        "large",
                        "SAM 2 Large (224.4M params) - Best quality, high memory",
                    ),
                ],
                default="base_plus",
                help_text="SAM 2 model size affects quality vs memory usage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="analysissession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysissession",
            name="analysis_type",
            field=models.CharField(
                choices=[
                    ("thermal_anomaly", "Thermal Anomaly Detection"),
                    ("material_mapping", "Material Mapping"),
                    ("insulation_analysis", "Insulation Analysis"),
                    ("air_leakage", "Air Leakage Detection"),
                    ("structural_analysis", "Structural Analysis"),
                ],
                default="thermal_anomaly",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analysissession",
            name="sam2_session_id",
            field=models.CharField(
                blank=True, help_text="UUID from SAM 2 service", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="analysissession",
            name="target_materials",
            field=models.JSONField(
                default=list, help_text="List of materials to focus on"
            ),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["status"], name="analysis_an_status_d73abf_idx"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["sam2_model"], name="analysis_an_sam2_mo_466487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["analysis_type"], name="analysis_an_analysi_a24d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["created_at"], name="analysis_an_created_0bbbdd_idx"
            ),
        ),
    ]
